EsashikaArtCatalogue/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('catalogue/', include('catalogue.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

catalogue/urls.py
import os.path
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'catalogue'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

catalogue/models.py
from django.db import models

class Opus(models.Model):
    opus_title = models.CharField(max_length=200)
    opus_description = models.TextField()
    opus_image = models.ImageField(upload_to='opus_image', null=True)

    class Meta:
        verbose_name_plural = 'Opuses'

    def __str__(self):
        return self.opus_title

catalogue/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponse
from .models import Opus

class IndexView(generic.ListView):
    template_name = 'catalogue/index.html'

    def get_queryset(self):
        return Opus.objects.all()[:5]

class DetailView(generic.DetailView):
    model = Opus
    template_name = 'catalogue/detail.html'

catalogue/templates/catalogue/base.html
<!DOCTYPE html>
<html>
	<head>
		{% include 'catalogue/common_head.frag.html' %}
		<title>{% block title %}Esashika Art Catalogue{% endblock %}</title>
	</head>
	<body>
		<div class="container">
			<nav class="navbar">
				<div class="navbar-brand">
					<a class="navbar-item" href="{% url 'catalogue:index' %}">Esashika Art Catalogue</a>
				</div>
				<div class="navbar-menu">
					<div class="navbar-end">
						<div class="navbar-item">
							<div class="buttons">
								<a class="button is-light">Contact</a>
							</div>
						</div>
					</div>
				</div>
			</nav>
			<section class="section">
				{% block content %}{% endblock %}
			</section>
			<footer class="footer">
				<div class="content has-text-centered">
					<p>This website is created by ESASHIKA Kaoru</p>
				</div>
			</footer>
		</div>
	</body>
</html>

catalogue/templates/catalogue/common_head.frag.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
<style type="text/css">
  .tile a, .tile a:hover, .tile a:visited, .tile a:active {
	  color: inherit;
	  text-decoration: none;
  }
</style>

catalogue/templates/catalogue/detail.html
{% extends 'catalogue/base.html' %}
{% block title %}Opus Detail: {{ opus.opus_title }}{% endblock %}
{% block content %}
<div class="columns is-centered">
	<div class="column has-text-centered">
		<img src='{{ opus.opus_image.url }}' alt="image of {{ opus.opus_title }}"></img>
	</div>
</div>
<div class="columns is-centered">
	<div class="columns is-6 box">
		<div class="column" style="display: flex;">
		<div>
			<table class="table">
				<tbody>
					<tr>
						<td>「{{ opus.opus_title }}」</td>
					</tr>
					<tr>
						<td>F4・水彩</td>
					</tr>
					<tr>
						<td>10万円（売約済み）</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div style="display: flex; align-items: center;">
			<p style="margin-left: 1em;">{{ opus.opus_description }}</p>
		</div>
		</div>
	</div>
</div>
{% endblock %}

catalogue/templates/catalogue/index.html
{% extends 'catalogue/base.html' %}
{% block title %}Esashika Art Catalogue{% endblock %}
{% block content %}

{% if opus_list %}
<div class="tile is-ancestor is-vertical">
	<div class="tile is-parent">
		{% for opus in opus_list %}
		<div class="tile is-child box is-4">
			<a href="{% url 'catalogue:detail' opus.id %}">
				<img src='{{ opus.opus_image.url }}' alt="a picture of {{ opus.opus_title }}"></img>
				<p class="title" style="text-align: right;">{{ opus.opus_title }}</p>
			</a>
		</div>
		{% if forloop.counter|divisibleby:3 %}
	</div><div class="tile is-parent">
		{% endif %}
		{% endfor %}
	</div>
</div>
{% else %}
<p>No opuses are available.</p>
{% endif %}

{% endblock %}